### ISSUE TITLE
on linux does not remove empty lines 

### ISSUE THREAD

**Issue by NikosEfthias** [shardulm94/vscode-trailingspaces#2] opened 2016-04-14 18:28 UTC
if theres space after empty line removes them but does not entirely remove empty lines

**Comment by shardulm94** [comment] 2016-04-14 19:13
@NikosEfthias This is by feature. Empty lines are usually a good practice to visually space out different regions in the code; especially between two functions or two blocks of code inside a function.

Can you provide me with a use case where deleting the whole line would be beneficial rather than just deleting the trailing spaces at the end of it?

**Comment by NikosEfthias** [comment] 2016-04-14 19:15
personally i would like to remove empty lines too i added \n into regex but it aint work is there any way to get it to work ?

**Comment by shardulm94** [comment] 2016-04-14 19:27
Indeed, adding `\n` into the regex should have deleted the new lines. Will work on a fix for this.

**Comment by NikosEfthias** [comment] 2016-04-14 19:28
great :) thank you

**Comment by NikosEfthias** [comment] 2016-04-14 19:29
![](http://i.imgur.com/z8CR2DV.png) current setting whis doesnt work is this

**Closed** 2016-04-14 23:16 UTC
Labels: bug

**Comment by shardulm94** [comment] 2016-04-14 23:32
Can you update the extension to 0.2.8 and let me know if the issue has been resolved?
Also, instead of using `[ \t\n]+` as the `regexp`, I would suggest using `[\\s]+`. This regexp would be consistent across both Unix (LF) as well as Windows (CRLF) line endings.

`[\\s]+` is effectively equivalent to `[ \t\r\n\f]+`.

**Comment by NikosEfthias** [comment] 2016-04-15 03:42
great this was what i was talking about :) thank you so much @shardulm94  i hate those blank lines :) if i vant to annotate my script i usually go with comments 

Btw why  while escaping space character you used double `\` in your example `\\s`  like this i think `\s` shoud do the trick . aint ?

**Comment by shardulm94** [comment] 2016-04-15 09:24
`' ', '\t', '\n', '\r', '\f'` are all character literals. Each of those has a corresponding ASCII value which we want to match with our regex. `\s` on the other hand is not a character literal per se, it is a meta-sequence in regex and needs to be escaped when passed as a string.

Note: While creating a `RegExp` object in javascript, you can avoid the need for escaping by using the `RegExp` literal notation. For example, both notations below result in the same `RegExp` object.
```js
var a = new RegExp("[\\s]+");
var b = /[\s]+/;
```

**Comment by shardulm94** [comment] 2016-04-16 19:24
@NikosEfthias Hey, do you mind updating the review on the visual studio marketplace if this issue is resolved for you?

**Comment by NikosEfthias** [comment] 2016-04-19 18:48
ah yeah sorry :)

**Comment by shardulm94** [comment] 2016-04-19 19:44
thanks :smile:

**Comment by NikosEfthias** [comment] 2016-04-20 19:06
there was an update yesterday and it again stopped working and this time highlighting wont work either im using ubuntu 15.10

**Comment by shardulm94** [comment] 2016-04-20 19:51
Well, that is strange! I am not able to reproduce it on the latest version of the extension. Can you post all your settings related to trailing spaces? Also, if you have a log of the same, it may help me dig deeper.

**Comment by NikosEfthias** [comment] 2016-04-20 19:54
![](http://i.imgur.com/Vl7LCBT.png)

and as you see it wont highlight the line or spaces

**Comment by shardulm94** [comment] 2016-04-20 19:57
Can you go to Help > Toggle Developer Tools and check what errors it is displaying?

**Comment by NikosEfthias** [comment] 2016-04-20 20:01
![](http://i.imgur.com/tlSewC4.png)

**Comment by shardulm94** [comment] 2016-04-20 20:08
@NikosEfthias Sorry that I have to bug you again! Only because I am not able to reproduce it! Can you expand the error that is shown? It will help me fetch the line where it is originating. 

Also, I will setup a linux virtual machine tomorrow to test the extension there.

**Comment by NikosEfthias** [comment] 2016-04-20 20:10
![](http://i.imgur.com/635V3oz.png) i dont know if thats helpfull but i also see the its originating from threadService.ts line 199

**Comment by shardulm94** [comment] 2016-04-20 20:14
Sadly that doesn't clear things up much :(
I will only be able to check this tomorrow as I don't have access to my desktop today.

**Comment by NikosEfthias** [comment] 2016-04-20 20:15
its okay anyway im gonna sleep too soon its midnight here

**Comment by shardulm94** [comment] 2016-04-21 19:04
@NikosEfthias Not able to reproduce this on a fresh ubuntu 15.10. Can you just try reinstalling the extension?

**Comment by NikosEfthias** [comment] 2016-04-21 19:41
now its working after reinstalling @shardulm94

**Comment by shardulm94** [comment] 2016-04-21 19:44
Not sure why it failed. Maybe there was some issue with how the update was handled.

**Comment by NikosEfthias** [comment] 2016-04-21 19:45
the weirdest thing is that it worked a day after update and then started to fail

**Comment by shardulm94** [comment] 2016-04-21 19:47
Hmm! Yes, that's weirder! :confused: Will keep an eye out for this.

**Comment by NikosEfthias** [comment] 2016-04-21 19:48
you got the error message :)
