### ISSUE TITLE
Unnecessary status bar noise: "No trailing spaces to delete!"

### ISSUE THREAD

**Issue by marcelocantos** [shardulm94/vscode-trailingspaces#11] opened 2017-05-07 19:52 UTC
Whenever I save, the status bar reports "No trailing spaces to delete!". This message serves no purpose and merely adds distracting noise to the status bar. Is there any chance of removing it or making it optional?

This message comes up even when there are trailing spaces (immediately after a "Deleting…" message, which flashes momentarily), but don't want to see it under either circumstance.

**Comment by shardulm94** [comment] 2017-05-08 16:23
Agreed. The "No trailing spaces to delete!" message on saving is unnecessary. Planned new behavior -
On file save, if there were trailing spaces, the "Deleted..." message will be shown. If there were no trailing spaces, no message will be shown.
When the functionality is explicitly called using the "Delete Trailing Spaces" command, "No trailing spaces to delete!" message will still be shown as a feedback to the explicit user action.

Regarding the second issue, the root cause is that the delete functionality is being called twice on save (one when the user saves the file, second when the extension saves the file after deleting trailing spaces). The second run overwrites the feedback from the first, but this should not be a problem now since the second run will not find any spaces and no message will be shown.

**Comment by grokky1** [comment] 2017-09-23 16:42
Would be nice to have an option to turn this off completely.

**Comment by shardulm94** [comment] 2017-09-23 16:45
Sorry, this is taking so much time. Grad school is getting to me. I have this functionality setup in the develop branch but don't want to release anything before I test thoroughly. I will try to get this out next week.

**Comment by grokky1** [comment] 2017-09-23 16:54
@shardulm94 Don't worry about it, it's not that important. 😆

I enjoy the extension regardless of this minor issue... Thanks. 👍

**Comment by gimbo** [comment] 2019-02-16 09:59
Hello! I'd just like to add my vote to this one, if there's any chance of making it happen... Loving the extension otherwise, many thanks for this great work!

**Comment by shardulm94** [comment] 2019-03-28 20:31
I am working on fixing this. I think the status bar message is especially important when the user explicitly triggers the command. The message serves as feedback loop to the users action, even when there is nothing to delete. It is also important when using the "Trim on save" feature since we are modifying the user's file, but I agree it is noise when there are no spaces to delete in this case.

Working on two changes for the next release
New behaviour: Do not show the status bar message when trimming automatically and there are no edits.
New feature: Add option to completely suppress status bar messages.

**Comment by shardulm94** [comment] 2019-03-29 00:22
@gimbo Can you try to see if the new beta release solves this?
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc2
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by gimbo** [comment] 2019-04-04 07:32
@shardulm94 Hi there - sorry for delay, but yes, I can confirm that that release does solve it - it seems totally silent even when it _does_ trim space on save.

**Comment by shardulm94** [comment] 2019-04-07 02:00
Released in v0.3.0 available in marketplace

**Closed by shardulm94** 2019-04-07 02:00 UTC
Labels: enhancement
