### ISSUE TITLE
on split window view trailing-space extension throws exception

### ISSUE THREAD

**Issue by NikosEfthias** [shardulm94/vscode-trailingspaces#7] opened 2016-04-22 08:12 UTC
![](https://camo.githubusercontent.com/045dbfd65429ae578bd814dbef74a9e1a09234f8/687474703a2f2f692e696d6775722e636f6d2f36333556336f7a2e706e67)

**Comment by shardulm94** [comment] 2016-04-22 08:14
On the git diff view? or just any split editor?

**Comment by NikosEfthias** [comment] 2016-04-22 08:15
i just splitted the editor in order to edit 2 files simultaneously and it crashed

**Comment by shardulm94** [comment] 2016-04-22 08:17
Thanks! will investigate this on linux tonight. Not able to reproduce on windows. Thanks for this! You have been a great help!

**Comment by NikosEfthias** [comment] 2016-04-22 08:18
:) i thank you for this extension

**Comment by shardulm94** [comment] 2016-04-22 18:59
Not able to reproduce. Certainly looks like some issue with the extension. Will keep this open for now and investigate further.

**Comment by NikosEfthias** [comment] 2016-04-27 17:50
![](http://i.imgur.com/eqEmC6O.png) again this error started and this time completely i cannot use extension even after  removing and installing back

**Comment by shardulm94** [comment] 2016-04-27 18:48
@NikosEfthias The extension is not able to read its configuration. Pretty sure this issue is directly related to [this issue in vscode](https://github.com/Microsoft/vscode/issues/5649). The May release of vscode should fix it.

**Comment by shardulm94** [comment] 2016-04-27 22:21
Also, I was successfully able to reproduce it in the insiders build. Will keep an eye on this when the new version releases.

**Comment by NikosEfthias** [comment] 2016-04-28 11:24
so at the moment we are waiting for a new release :)

**Comment by shardulm94** [comment] 2016-05-11 19:52
Fixed by https://github.com/Microsoft/vscode/commit/957653954a359386045cabe6684b280414d6083d https://github.com/Microsoft/vscode/issues/5649
Updating VSCode to the latest version should resolve it.

**Closed by shardulm94** 2016-05-11 19:52 UTC
Labels: vscode-bug
